
### EXPORT_ALL POLICY ###
---
apiVersion: routingpolicies.eda.nokia.com/v1alpha1
kind: Policy
metadata:
  name: export-all
  namespace: eda
  labels: {}
  annotations: {}
spec:
  defaultAction:
    bgp:
      asPathRemove: false
      localPreference: null
      setOrigin: ''
      asPathPrepend: null
      asPathReplace: []
    policyResult: accept
  statement:
    - action:
        bgp:
          asPathRemove: false
        policyResult: accept
      name: accept-all




### IMPORT_ALL POLICY ###
---
apiVersion: routingpolicies.eda.nokia.com/v1alpha1
kind: Policy
metadata:
  name: import-all
  namespace: eda
  labels: {}
  annotations: {}
spec:
  defaultAction:
    bgp:
      asPathRemove: false
      localPreference: null
      setOrigin: ''
      asPathPrepend: null
      asPathReplace: []
    policyResult: accept
  statement:
    - action:
        bgp:
          asPathRemove: false
        policyResult: accept
      name: accept-all




### EXPORT_TO_UNDERLAY POLICY ###
---
apiVersion: routingpolicies.eda.nokia.com/v1alpha1
kind: Policy
metadata:
  name: export-to-underlay
  namespace: eda
  labels: {}
  annotations: {}
spec:
  defaultAction:
    bgp:
      asPathRemove: false
      localPreference: null
      setOrigin: ''
      asPathPrepend: null
      asPathReplace: []
    policyResult: accept
  statement:
    - action:
        bgp:
          asPathRemove: false
        policyResult: accept
      name: accept-all




### IMPORT_FROM_UNDERLAY POLICY ###
---
apiVersion: routingpolicies.eda.nokia.com/v1alpha1
kind: Policy
metadata:
  name: import-from-underlay
  namespace: eda
  labels: {}
  annotations: {}
spec:
  defaultAction:
    bgp:
      asPathRemove: false
      localPreference: null
      setOrigin: ''
      asPathPrepend: null
      asPathReplace: []
    policyResult: accept
  statement:
    - action:
        bgp:
          asPathRemove: false
        policyResult: accept
      name: accept-all
